/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_fogbox_NativeLib */

#ifndef _Included_com_android_fogbox_NativeLib
#define _Included_com_android_fogbox_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_fogbox_NativeLib
 * Method:    setAppName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_android_fogbox_NativeLib_setAppName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_android_fogbox_NativeLib
 * Method:    sendFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_android_fogbox_NativeLib_sendFile
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     com_android_fogbox_NativeLib
 * Method:    closezip
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_fogbox_NativeLib_closezip
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
